# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout Directory
        run: |
          realpath .
          ls
      - name: Checkout Git Log
        run: git log --pretty=format:%H
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up User
        run: |
          git config user.name manhlamabc123
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pandas PyGithub Requests tqdm scikit-learn torch imblearn scipy gdown
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install DefectGuard
        run: |
          pip install -i https://test.pypi.org/simple/ defectguard==0.1.26
      - name: Check DefectGuard Version
        run: |
          defectguard --version
      - name: Run DefectGuard
        run: |
          realpath .
          ls
          run: git log --pretty=format:%H
          defectguard -models deepjit -dataset platform -repo . -commit_hash 4f60b59efa6aba1ee4504c643cad28b082e78417 -main_language Python
